FROM nginx:alpine

COPY config.template.js /usr/share/nginx/html/config.template.js
COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD sh -c "envsubst '\$API_URL' < /usr/share/nginx/html/config.template.js > /usr/share/nginx/html/config.js && nginx -g 'daemon off;'"