apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
    - name: api
      image: ecommerce-api:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      env:
        - name: API_INTERNAL_PORT
          value: "3000"